### ISSUE TITLE
기능 추가 검토 요청

### ISSUE THREAD

**Issue by techman8600** [adc000/MapleTimer#1]
안녕하세요. 재획타이머 관련하여 잘 만들어주셔서 감사합니다.
매우 잘 사용하고 있습니다.

한가지 기능 추가 요청하고 싶은부분이 있어서 이슈 남깁니다.
혹시 매획타이머를 추가해주실 수 있으실까요?

직업이 불독인데 재획타이머외에 2분마다 매소회수를 위한 타이머를 따로 쓰고 있다보니 혹시 음성출력 가능한 메획타이머
기능 추가 가능하시다면 부탁드립니다~!!

만약 한가지더 가능하다면 불독이다 보니 포이즌리전 또한 다른 타이머 같이 사용중입니다.
가능하시다면! 요부분도 기능 추가 검토 부탁드립니다!!!!

**Comment by adc000** [comment]
헉 확인이 늦었네요. 단순 매획 타이머는 고랴해보겠습니다.
포이즌 리전은 작동 방식을 제가 몰라서.. 설명해주시면 고려해보겠으나 범용성이 없을 것 같아 어려울 수 있습니다

**Comment by adc000** [comment]
포이즌 리전의 경우 동작 방식을 알려주시면 현재 기능만으로 사용 가능하도록 안내 가능할 것 같습니다.
메소 회수 타이머는 v0.10에 추가했습니다.
