### ISSUE TITLE
QHD (2560x1440) 해상도 지원 여부?

### ISSUE THREAD

**Issue by Jisean** [adc000/MapleTimer#2]
안녕하세요 잘 사용하고 있습니다.

저는 윈도우 해상도를 2560x1440으로 두고 메이플은 1920x1080 창모드 최적 모드로 사용하고 있습니다.

v0.6 버전에서는 1336x768으로 할 경우 맞게 나왔는데 이번에 v0.7 버전에서 추가 해상도 업데이트 이후로 전부 다 화면에 맞지 않게 나오고 있습니다.

차후 업데이트에서는 이 부분이 지원이 가능한지 문의 드립니다.
![캡처](https://github.com/adc000/MapleTimer/assets/20578154/b2635a5a-9b81-4d92-86f5-d5ee7d5bcadf)

**Comment by adc000** [comment]
확인이 한번 필요할 것 같네요. 범용 offset이 잘못 되어있을 수도 있을 것 같습니다. (최근에 저도 틀어진것 같아요)
별개로 임시로는 중간쯤에있는 화살표의 버튼을 누르면 offset조정이 가능합니다

**Comment by adc000** [comment]
offset 버튼을 이용하여 우선 조정해 보심을 추천드립니다. 최적 비율이 어떤 방식으로 조절하는지 화면마다 다르게 나오는 것 같아 generalizing이 안되는 것 같습니다 ㅠ 우선 offset사용해보시고 잘 안되면 다시 한번 issue 남겨주세요
